### PR TITLE
Add `sudo` to `role` & map to `user` and `group` in SSHKit.Context.

### PR DESCRIPTION
**Pull request by derekkraan**
Can specify either `user` or `group` or both.

Example:

```elixir
role(:app, user: "bob", sudo: [user: "www"])
```

### CODE REVIEW

**Comment by derekkraan** [comment]
The tests on `master` appear to also be failing, because of an internal Mix API that has changed? https://github.com/bitwalker/distillery/issues/431

**Comment by derekkraan** [comment]
Hi,

I've rebased on master to get the tests green. We have been using this in our workflow for a couple of months now. The basic use case is: you want to log in with your own user but run commands as another user using `sudo`. This is pretty much required for any corporate setup that uses `kerberos` for example, where not everyone is using the same credentials to log in to servers and deploy.

Cheers
Derek

**Comment by brienw** [comment]
Thanks @derekkraan this is great! We just talked more about this internally and decided it might be best to add a way to just specify any/all context options via bootleg config. That way the sudo support will be available, in addition to `env` and `umask` and whatever else anybody else may need.

I've created a new issue to track this, and we'll have it as part of the `0.9.0` release

**Comment by brienw** [comment]
Closing this ticket, we'll track this `sudo` support as part of that ticket #255

**Pull request closed without merging**
