### PR TITLE
Add ability to pull from repo url

### PR DESCRIPTION
**Pull request by StephaneRob**
- require that remote servers already have the authentication set up for their git provider
- Need to add tests

### CODE REVIEW

**Comment by StephaneRob** [comment]
fix #175

**Comment by brienw** [comment]
WHOA! thank you for this! I don't know if i'll have time to look it over today, but i'll give it a peak next week (or possibly this weekend)

**Comment by brienw** [comment]
Ok, jeesh, we finally just got that big DSL refactor merged in. Would you mind updating this branch? Hopefully the merge conflicts aren't too major if there are any. 

NOTE: After the refactor I just merged in `use Bootleg.Config` has been deprecated in favor of `use Bootleg.DSL` in order to pull in all the DSL macros.

**Comment by StephaneRob** [comment]
I've just seen the DSL refactor, it's great !
I'm going to update this branch with last commits. I didn't have time to add tests this week but i'll work on this weekend.

Do you have any idea about the best way to integrate this test ?

**Comment by brienw** [comment]
I would look at setting up a fixture project that _also_ contains a second checkout of the git repo somewhere locally (could even be inside the docker container). Then add the second local repo as a *remote* of the main project git repo. That should allow you to test that your pull method works. You could have the 'remote' repo set up to be like one commit ahead or behind so that you can verify commit hashes and assert that you see the one you would expect.

**Comment by brienw** [comment]
Thank you @StephaneRob and @rjanja, this is rad!

**Pull request merged**
